name: Build Electron App

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure the version matches your project

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install Electron Packager
        run: npm install electron electron-builder --save-dev

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}  # Optional, if needed
        run: npm run electron-build  # Define this in your package.json to build the Electron app

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ElectronApp  # Name of the artifact
          path: dist/  # Path where the Electron app is built
