name: Build Electron App

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ensure the version matches your project

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install Electron Packager
        run: npm install electron electron-builder --save-dev

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}  # Pass the GitHub Token here
        run: npm run electron-build  # Define this in package.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: ElectronApp
          path: dist/  # Path where the Electron app is built

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Git Tag  # NEW: This creates a new tag for the release
        run: |
          git tag v1.0.0  # Replace with a versioning scheme of your choice
          git push origin v1.0.0

      - name: Upload Electron build to GitHub releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.dmg, dist/*.exe, dist/*.AppImage  # Add formats you want to support
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Pass the GitHub Token here
